
const GET_LATEST_LINKS = 'GET_LATEST_LINKS';
const GET_LATEST_LINKS_SUCCESS = 'GET_LATEST_LINKS_SUCCESS';
const GET_LATEST_LINKS_FAILURE  = 'GET_LATEST_LINKS_FAILURE'

const DELETE_LINK = 'DELETE_LINK';
const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
const DELETE_LINK_FAILURE  = 'DELETE_LINK_FAILURE';

export default {
    GET_LATEST_LINKS,
    GET_LATEST_LINKS_SUCCESS,
    GET_LATEST_LINKS_FAILURE,
    DELETE_LINK,
    DELETE_LINK_SUCCESS,
    DELETE_LINK_FAILURE
}