
const GET_TOPICS = 'GET_TOPICS';
const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
const GET_TOPICS_FAILURE  = 'GET_TOPICS_FAILURE'

const ADD_TOPIC = 'ADD_TOPIC';
const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
const ADD_TOPIC_FAILURE  = 'ADD_TOPIC_FAILURE';

const DELETE_TOPIC = 'DELETE_TOPIC';
const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
const DELETE_TOPIC_FAILURE  = 'DELETE_TOPIC_FAILURE';

export default {
    GET_TOPICS,
    GET_TOPICS_SUCCESS,
    GET_TOPICS_FAILURE,
    ADD_TOPIC,
    ADD_TOPIC_SUCCESS,
    ADD_TOPIC_FAILURE,
    DELETE_TOPIC,
    DELETE_TOPIC_SUCCESS,
    DELETE_TOPIC_FAILURE
}