
const GET_TOPIC = 'GET_TOPIC';
const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';
const GET_TOPIC_FAILURE  = 'GET_TOPIC_FAILURE'

const GET_LINKS = 'GET_LINKS';
const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
const GET_LINKS_FAILURE  = 'GET_LINKS_FAILURE'

const ADD_LINK = 'ADD_LINK';
const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS';
const ADD_LINK_FAILURE  = 'ADD_LINK_FAILURE'

const DELETE_LINK = 'DELETE_LINK';
const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
const DELETE_LINK_FAILURE  = 'DELETE_LINK_FAILURE';

export default {
    GET_TOPIC,
    GET_TOPIC_SUCCESS,
    GET_TOPIC_FAILURE,
    GET_LINKS,
    GET_LINKS_SUCCESS,
    GET_LINKS_FAILURE,
    ADD_LINK,
    ADD_LINK_SUCCESS,
    ADD_LINK_FAILURE,
    DELETE_LINK,
    DELETE_LINK_SUCCESS,
    DELETE_LINK_FAILURE
}